name: digitalSTROM MQTT
version: "2.4.0"
slug: digitalstrom_mqtt
description: Unofficial community App connecting digitalSTROM to Home Assistant through MQTT Discovery.
url: "https://github.com/gaetancollaud/digitalstrom-mqtt/tree/master/home-assistant-app"
arch:
  - aarch64
  - amd64
init: false
services:
  - mqtt:need
image: "ghcr.io/gaetancollaud/digitalstrom-mqtt-haos"
ports:
  8080/tcp: null
options:
  digitalstrom_port: 8080
  digitalstrom_username: dssadmin
  invert_blinds_position: false
  meterings_enabled: true
  meterings_interval_seconds: 10
  log_level: INFO
  regenerate_api_key: false
schema:
  digitalstrom_host: str
  digitalstrom_port: "int(1,65535)"
  digitalstrom_username: str
  digitalstrom_password: "password?"
  invert_blinds_position: bool
  meterings_enabled: bool
  meterings_interval_seconds: "int(1,)"
  log_level: "list(TRACE|DEBUG|INFO|WARN|ERROR)"
  regenerate_api_key: bool
