// @no-cookie-jar
GET {{host}}/api/v1/apartment?include=installation,dsDevices,submodules,functionBlocks,zones,clusters,applications,dsServer,controllers,apiRevision,meterings
Authorization: Bearer {{api-key}}

###

// @no-cookie-jar
GET {{host}}/api/v1/apartment/status
Authorization: Bearer {{api-key}}
