// @no-cookie-jar
GET {{host}}/api/v1/apartment?include=dsDevice
Authorization: Bearer {{api-key}}

###

// @no-cookie-jar
GET {{host}}/api/v1/apartment/status?include=zones
Authorization: Bearer {{api-key}}
