// @no-cookie-jar
GET {{host}}/api/v1/apartment/dsDevices
Authorization: Bearer {{api-key}}

###
// @no-cookie-jar
GET {{host}}/api/v1/apartment/functionBlocks
Authorization: Bearer {{api-key}}

###
PATCH {{host}}/api/v1/apartment/dsDevices/303505d7f8000000000000400013befc00/status
Authorization: Bearer {{api-key}}
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/functionBlocks/303505d7f8000000000000400013befc00/outputs/brightness/value",
    "value": 0
  }
]


###
// @no-cookie-jar
GET {{host}}/api/v1/apartment/submodules
Authorization: Bearer {{api-key}}


###
GET {{host}}/api/v1/apartment/dsDevices
Authorization: Bearer {{api-key}}

###
GET {{host}}/api/v1/apartment/dsDevices/303505d7f8000000000000400013befc00
Authorization: Bearer {{api-key}}

###
GET {{host}}/api/v1/apartment/dsDevices/status
Authorization: Bearer {{api-key}}

###
GET {{host}}/api/v1/apartment/dsDevices/303505d7f8000000000000400013befc00/status
Authorization: Bearer {{api-key}}
